import { supabase } from './supabase';

// This Public Key should match the one generated by web-push on your backend
const VAPID_PUBLIC_KEY = 'BOQS5jGeY1uyMDkK7BocruEAkQVcWx3sSPe7VBVvoj_UpNT5FZmr52hu9izrT9i6M5J2ScIJhOd6AYhzWHRiAyI';

function urlBase64ToUint8Array(base64String: string) {
  const padding = '='.repeat((4 - base64String.length % 4) % 4);
  const base64 = (base64String + padding)
    .replace(/\-/g, '+')
    .replace(/_/g, '/');

  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);

  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

export async function subscribeToPush() {
  if (!('serviceWorker' in navigator) || !('PushManager' in window)) {
    console.warn('Push messaging is not supported in this browser.');
    return null;
  }

  try {
    // Check if we already have a registration that is active
    let registration = await navigator.serviceWorker.getRegistration();
    
    // If no active registration or it's not ready, try to wait briefly
    if (!registration || !registration.active) {
      registration = await Promise.race([
          navigator.serviceWorker.ready,
          new Promise((_, reject) => setTimeout(() => reject(new Error("SW Timeout")), 3000))
      ]) as ServiceWorkerRegistration;
    }
    
    if (!registration || !registration.pushManager) {
        console.warn("Push Manager not available on registration");
        return null;
    }

    // Check for existing subscription
    let subscription = await registration.pushManager.getSubscription();
    
    if (!subscription) {
      const convertedVapidKey = urlBase64ToUint8Array(VAPID_PUBLIC_KEY);
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedVapidKey
      });
    }

    const { data: { user } } = await supabase.auth.getUser();
    if (user && subscription) {
      const { error } = await supabase.from('push_subscriptions').upsert({
        user_id: user.id,
        subscription: subscription.toJSON(),
      }, { onConflict: 'user_id' });
      
      if (error) console.error("Failed to save push subscription to DB:", error);
    }

    return subscription;
  } catch (error) {
    console.error('Push subscription failed (non-critical):', error);
    return null;
  }
}

export async function checkNotificationPermission() {
  if (!('Notification' in window)) return 'unsupported';
  return Notification.permission;
}